# Generated by Django 6.0 on 2026-02-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_company_branch_locations_company_brand_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_key",
                    models.CharField(
                        choices=[
                            ("registration", "Business Registration"),
                            ("tax", "Tax / GST / EIN"),
                            ("proof", "Government Proof"),
                            ("signatory", "Authorized Signatory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="company_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.company",
                    ),
                ),
            ],
        ),
    ]
