# Generated by Django 6.0 on 2026-02-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_companydocument"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companydocument",
            unique_together={("company", "document_key")},
        ),
    ]
