# Generated by Django 6.0 on 2026-02-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_companydocument_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="brand_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
    ]
