# Generated by Django 6.0 on 2026-02-09 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_company_brand_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=20)),
                ("profession", models.CharField(max_length=100)),
                ("other_profession", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=255)),
                ("travel_willingness", models.CharField(max_length=50)),
                ("availability_status", models.CharField(max_length=50)),
                ("work_modes", models.JSONField(default=list)),
                ("experience_level", models.CharField(max_length=50)),
                ("skills", models.JSONField(default=list)),
                ("qualification", models.CharField(blank=True, max_length=255)),
                ("institution", models.CharField(blank=True, max_length=255)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seeker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSeekerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("resume", "Resume"), ("work_proof", "Work Proof")],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="seeker_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.jobseekerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "document_type")},
            },
        ),
    ]
