# Generated by Django 6.0 on 2026-02-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_jobseekerprofile_jobseekerdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="availability_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="experience_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="mobile",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="profession",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="travel_willingness",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
