# Generated by Django 6.0 on 2026-02-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_jobseekerprofile_availability_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="seeker_profiles/"
            ),
        ),
    ]
