# Generated by Django 6.0 on 2026-03-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_jobseekerprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
