# Generated by Django 6.0 on 2026-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_wallet_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="encrypted_private_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="wallet_type",
            field=models.CharField(
                choices=[("managed", "Managed"), ("external", "External")],
                default="external",
                max_length=20,
            ),
        ),
    ]
