# Generated by Django 6.0 on 2026-03-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_customuser_encrypted_private_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_wallet_active",
            field=models.BooleanField(default=False),
        ),
    ]
