# Generated by Django 6.0 on 2026-03-10 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_customuser_is_wallet_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Fiat Deposit (Treasury to Managed)"),
                            ("escrow_lock", "Escrow Lock (Managed to Smart Contract)"),
                            ("income", "Project Income (Smart Contract to Managed)"),
                            ("withdrawal", "Withdrawal (Managed to External Wallet)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=18)),
                ("currency", models.CharField(default="MATIC", max_length=10)),
                ("tx_hash", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
