# Generated by Django 6.0 on 2026-03-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_wallettransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("pending", "Pending Approval"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
    ]
