# Generated by Django 6.0 on 2026-02-15 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_nature",
                    models.CharField(
                        choices=[("Professional", "Professional"), ("Local", "Local")],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("Immediate", "Immediate"),
                            ("Flexible", "Flexible"),
                            ("Scheduled", "Scheduled"),
                        ],
                        default="Flexible",
                        max_length=20,
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                (
                    "experience_level",
                    models.CharField(blank=True, default="Intermediate", max_length=50),
                ),
                ("portfolio_required", models.BooleanField(default=False)),
                ("deliverables", models.TextField(blank=True)),
                (
                    "professional_duration",
                    models.CharField(blank=True, default="1-4 weeks", max_length=50),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=20)),
                (
                    "distance_preference",
                    models.CharField(blank=True, default="5km", max_length=20),
                ),
                (
                    "work_location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Home", "Home"),
                            ("Office", "Office"),
                            ("Shop", "Shop"),
                            ("Construction Site", "Construction Site"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tools_provided_by",
                    models.CharField(
                        blank=True,
                        choices=[("Worker", "Worker"), ("Me", "Me")],
                        max_length=20,
                    ),
                ),
                (
                    "local_time_estimate",
                    models.CharField(blank=True, default="Half Day", max_length=50),
                ),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time_slot", models.TimeField(blank=True, null=True)),
                ("certification_required", models.BooleanField(default=False)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("Fixed", "Fixed"), ("Hourly", "Hourly")],
                        default="Fixed",
                        max_length=20,
                    ),
                ),
                ("budget_min", models.IntegerField(blank=True, null=True)),
                ("budget_max", models.IntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("contact_method", models.CharField(default="Chat", max_length=20)),
                ("show_profile", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
