# Generated by Django 6.0 on 2026-03-02 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("jobs", "0003_job_status"),
        ("work", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_source",
                    models.CharField(
                        choices=[("user", "User Job"), ("company", "Company Job")],
                        max_length=20,
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work.workpost",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "company_job"), ("user", "user_job")},
            },
        ),
    ]
