# Generated by Django 6.0 on 2026-03-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_savedjob"),
        ("jobs", "0004_job_is_deleted"),
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="company_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="jobs.job",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="user_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="work.workpost",
            ),
        ),
    ]
