# Generated by Django 6.0 on 2026-03-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_alter_jobapplication_company_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="company_name_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_location_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_title_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Applied", "Applied"),
                    ("Under Review", "Under Review"),
                    ("Interview", "Interview"),
                    ("Selected", "Selected"),
                    ("Rejected", "Rejected"),
                ],
                default="Applied",
                max_length=20,
            ),
        ),
    ]
