# Generated by Django 6.0 on 2026-03-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_jobapplication_company_name_snapshot_and_more"),
        ("jobs", "0004_job_is_deleted"),
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="company_name_snapshot",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="job_location_snapshot",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="job_title_snapshot",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="status",
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="company_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.job",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="user_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="work.workpost",
            ),
        ),
    ]
