# Generated by Django 6.0 on 2026-03-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_remove_jobapplication_company_name_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shortlisted", "Shortlisted"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
