# Generated by Django 6.0 on 2026-03-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_alter_jobapplication_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Review", "Review"),
                    ("Shortlisted", "Shortlisted"),
                    ("Interview", "Interview"),
                    ("Selected", "Selected"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
