# Generated by Django 6.0 on 2026-03-09 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_jobseekerprofile_profile_picture"),
        ("applications", "0009_applicationactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("deliverables", models.JSONField(default=list)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "payment_method",
                    models.CharField(default="Blockchain Escrow", max_length=50),
                ),
                ("terms", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Agreement Pending"),
                            ("accepted", "Accepted by Seeker"),
                            ("funded", "Funded"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("paid", "Payment Released"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tx_hash", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.jobseekerprofile",
                    ),
                ),
            ],
        ),
    ]
