# Generated by Django 6.0 on 2026-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_alter_workagreement_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workagreement",
            name="release_strategy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
