# Generated by Django 6.0 on 2026-03-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_workagreement_release_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="workagreement",
            name="submission_attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="agreement_submissions/"
            ),
        ),
        migrations.AddField(
            model_name="workagreement",
            name="submission_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workagreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Agreement Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("in_progress", "InProgress"),
                    ("submitted", "Submitted"),
                    ("paid", "Payment Released"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
