# Generated by Django 6.0 on 2026-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_workagreement_submission_attachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workagreement",
            name="on_chain_id",
            field=models.IntegerField(
                blank=True, help_text="Agreement ID in the smart contract", null=True
            ),
        ),
    ]
