from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    JobSeekerRegisterView, 
    CompanyRegisterView, 
    LoginView, 
    MeView, 
    CompanyMeView, 
    CompanyProfileView, 
    CompanyDocumentUploadView, 
    JobSeekerProfileView, 
    JobSeekerDocumentView, 
    UpdateWalletView, 
    CreateManagedWalletView, 
    RelayTransactionView,
    CreateRazorpayOrderView,
    VerifyRazorpayPaymentView,
    WalletDashboardView,
    WithdrawMaticView,
    ChangePasswordView,
    AdminCompanyListView,
    AdminCompanyDetailView,
    AdminVerifyCompanyView,
    AdminUserListView,
    AdminUserStatusView,
    AdminStatsView,
    CompanyStatsView,
    MaticPriceView,
    NotificationView,
)

urlpatterns = [
    path('register/seeker/', JobSeekerRegisterView.as_view(), name='register_seeker'),
    path('register/company/', CompanyRegisterView.as_view(), name='register_company'),
    path("login/", LoginView.as_view(), name="login"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path('me/', MeView.as_view(), name='me'),
    path('company/me/', CompanyMeView.as_view(), name='company_me'),
    path("company/profile/", CompanyProfileView.as_view()),
    path('company/documents/', CompanyDocumentUploadView.as_view()),
    path("seeker/profile/", JobSeekerProfileView.as_view()),
    path("seeker/documents/", JobSeekerDocumentView.as_view()),
    path("update-wallet/", UpdateWalletView.as_view()),
    path("create-managed-wallet/", CreateManagedWalletView.as_view()),
    path('relay-transaction/', RelayTransactionView.as_view(), name='relay-transaction'),
    path('create-razorpay-order/', CreateRazorpayOrderView.as_view(), name='create-razorpay-order'),
    path('verify-razorpay-payment/', VerifyRazorpayPaymentView.as_view(), name='verify-razorpay-payment'),
    path('wallet-dashboard/', WalletDashboardView.as_view(), name='wallet-dashboard'),
    path('withdraw-matic/', WithdrawMaticView.as_view(), name='withdraw-matic'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('company/stats/', CompanyStatsView.as_view(), name='company_stats'),
    path('matic-price/', MaticPriceView.as_view(), name='matic_price'),
    path('notifications/', NotificationView.as_view(), name='notifications'),
    path('notifications/<int:pk>/', NotificationView.as_view(), name='notification_detail'),
    
    # Admin URLs
    path('admin/companies/', AdminCompanyListView.as_view(), name='admin_company_list'),
    path('admin/companies/<int:pk>/', AdminCompanyDetailView.as_view(), name='admin_company_detail'),
    path('admin/companies/<int:pk>/verify/', AdminVerifyCompanyView.as_view(), name='admin_verify_company'),
    path('admin/users/', AdminUserListView.as_view(), name='admin_user_list'),
    path('admin/users/<int:pk>/status/', AdminUserStatusView.as_view(), name='admin_user_status'),
    path('admin/stats/', AdminStatsView.as_view(), name='admin_stats'),
]
