# Generated by Django 6.0 on 2026-01-05 14:42

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_remote",
        ),
        migrations.RemoveField(
            model_name="job",
            name="seniority",
        ),
        migrations.AddField(
            model_name="job",
            name="application_deadline",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="application_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="application_method",
            field=models.CharField(
                choices=[("in_app", "Via App"), ("external", "External Link")],
                default="in_app",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="benefits",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="certifications",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="education",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_period",
            field=models.CharField(
                choices=[
                    ("yearly", "Yearly"),
                    ("monthly", "Monthly"),
                    ("hourly", "Hourly"),
                ],
                default="yearly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="screening_questions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="seniority_level",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="short_summary",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("on_site", "On-site"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default=datetime.date(2026, 1, 5),
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="employment_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_currency",
            field=models.CharField(default="INR", max_length=10),
        ),
    ]
