# Generated by Django 6.0 on 2026-02-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_remove_job_deadline_remove_job_is_remote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Paused", "Paused"),
                    ("Closed", "Closed"),
                ],
                default="Active",
                max_length=10,
            ),
        ),
    ]
