# Generated by Django 6.0 on 2026-03-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
